### PR TITLE
Normalization function fixed to support national locales in group-tit…

### PR DESCRIPTION
**Pull request by pepsik-kiev**
Normalization function fixed to support national locales in group-title for bouquets filenames
Normalization function fixed for picons name
Remove "self-written" xml escape & unescape. Use built-in standard xml.sax.saxutils
Add tvg-name tag support to "override" functionality and into the logic of forming an EPG Importer XML
Fixed epg url-link creation in *channels.sources.xml for EPG Importer E2 plugin
Fixed parsing m3u playlist when missing 'tvg-' tags in #EXTINF
Parsing algorithm #EXTINF (See the RFC link in the comments for the changes) changed - now we get all the tags in one line of python code 
Other minor changes =)
image

### CODE REVIEW

**Comment by lincsat** [comment]
I have tried both versions from the last Day. The first hangs  in the Parsing phase with a ValueError('too many values to unpack',)

The 2nd hangs at Creating Bouquets with IOError(2, 'No such file or directory')

**Comment by pepsik-kiev** [comment]
Everything works for me without any problems on BH and OpenBH. It should work for the rest. What image of E2 do you use? How did you launch the parser?

**Comment by lincsat** [comment]
I use OpenViX and tested on Vu+ Ultimo4k. I put the file in
/etc/enigma2/e2m3u2bouquet/ and launched from the command line with

/etc/enigma2/e2m3u2bouquet/e2m3u2bouquet.py

**Comment by pepsik-kiev** [comment]
1) Remove config.xml
2) Launch e2m3u2bouquet.py
3) Edit in config.xml in the sections <m3uurl> [[your_url_link]] and <epgurl> [[{your_epg_link}]]
4) Launch e2m3u2bouquet.py

**Comment by lincsat** [comment]
I get the same IOError but now it's immediately after the all channels
bouquet created message.

BTW, probably nothing to do with it but just updated to the latest ViX
build between previous test and this test.

**Comment by pepsik-kiev** [comment]
Show an example of any two lines from your playlist
#EXTINF:[duration] [key="key_value"*], title
[URL_LINK]
So that I can analyze and check with myself

**Comment by lincsat** [comment]
I have also tried another provider that uses the format -
http://URL/streams/hls/PASSWORD and this does succeed but generates an All
Channels bouquet only and gives an empty sort-current.xml


Here is an entry from the Playlist of the server using the standard link
#EXTINF:-1 tvg-id="ITV.uk" tvg-name="UKr: ITV1 Yorkshire East" tvg-logo="
https://ia801509.us.archive.org/24/items/LogoFolder1/Itv1.png"
group-title="UKr: Regional",UKr: ITV1 Yorkshire East
http://URL/USER/PASS/26540

And the playlist of the server using the shorter link
#EXTINF:-1   group-title="UK - Irish",BBC One Northern Ireland
http://URL/load/PASSWORD/80060.m3u8

**Comment by pepsik-kiev** [comment]
Does the error appear when the full or shortened link version used?

**Comment by lincsat** [comment]
The shortened link completes but only generates an All Bouquet and not
individual Bouquets. The standard link does not complete

**Comment by DougMac** [comment]
Thanks for the PR.

Don't know how I missed the built in for escape & unescape so that's something we'll take for the next version

As for the other changes:-

- Normalization function fixed to support national locales in group-title for bouquets filenames
Not sure what this fixing, the bouquet filenames can be anything as long as they match up in bouquets.tv and are valid filenames.

- Normalization function fixed for picons name
There are some specific picon naming rules which I believe your proposed changed have remove e.g. a * becomes the word star

- Add tvg-name tag support to "override" functionality and into the logic of forming an EPG Importer XML
I'll need to check back my notes to see if there was a reason we currently don't have tvg-name override support.

- Fixed epg url-link creation in *channels.sources.xml for EPG Importer E2 plugin
Can you please expand on what you've changed here?

- Fixed parsing m3u playlist when missing 'tvg-' tags in #EXTINF
There's a number of edge cases here which I believe your update will break. So it's likely we'll stick with what we have. There's a minor update for this in the next release

**Comment by pepsik-kiev** [comment]
> Normalization function fixed to support national locales in group-title for bouquets filenames
> Not sure what this fixing, the bouquet filenames can be anything as long as they match up in bouquets.tv and are valid filenames.

The original uses a construction with unicodedata.normalize; it does NOT work with Cyrillic characters in group-title and TITLE (channel name)

> There are some specific picon naming rules which I believe your proposed changed have remove e.g. a * becomes the word star

in my variant, you can specify ANY inconvenient or unnecessary characters to you. Again, the original - DOES NOT work if you slip the Cyrillic file name into

> Add tvg-name tag support to "override" functionality and into the logic of forming an EPG Importer XML

Added handling of the case when there is NO tvg-id, but there is tvg-name. Also added processing when there is no TITLE (channelName) in the line #EXTINF, but there is tvg-name.  "Nverride" functionality needs verification, I added intuitively by analogy with the existing one. I do not use it

> Fixed epg url-link creation in *channels.sources.xml for EPG Importer E2 plugin

Deleted [CDATA []] in the url section of the generated file. The only link left. See how similar sections look in rytec.sources.xml

**Comment by pepsik-kiev** [comment]
Characters not allowed in short file names, directories, and extensions: +=[]:;«,./?'space'
Characters not allowed in long file names, directories, and extensions: /\:*?«<>|

**Comment by pepsik-kiev** [comment]
I returned CDATA [[]], I will continue to analyze your code. For me, it’s already a mystery why you don’t use dictoxml, requests and other pure python libraries that can be included in the project as whl or egg. This makes the code much simpler and more compact.

**Comment by pepsik-kiev** [comment]
*** of the PIL module =) sorry for typo

**Comment by BliNeR-KeY** [comment]
image

**Comment by lincsat** [comment]
I got this build to run by changing the Picon path to what I use and then changing the testrun paths to match the normal paths.  However, it continues to skip channels without TVG-ID in the line on the M3U

**Comment by pepsik-kiev** [comment]
> I got this build to run by changing the Picon path to what I use and then changing the test run paths to match the normal paths. However, it continues to skip channels without TVG-ID in the line on the M3U

Bear with me a little and I will fix it. Now I am clearing the main logic of the code to simplify it. Tomorrow evening I will finish the logic by the lack of tags "tvg-id" or "tvg-name".  I also plan to add processing for the "url-tvg =" tag, which is usually present in the # EXTM3U IPTV provider playlist. What is the point of adding it to the config file again if it is in the header of the playlist? =) I'll try to add the setting "use EPG from the playlist header

Please be patient. Gradually, I’ll fix everything.

p.s. 
I also made the ipk file "for the lazy." If you need, I can put it out ;)

**Comment by pepsik-kiev** [comment]
**BliNeR-KeY** 
I have no problem with CrossEPG. All config files are created as needed and everything works as intended. I need a more detailed description of how you got the error as in the screenshot

**Comment by BliNeR-KeY** [comment]
> **BliNeR-KeY**
> I have no problem with CrossEPG. All config files are created as needed and everything works as intended. I need a more detailed description of how you got the error as in the screenshot
> I need an example of any two lines from your playlist
> 
> ```
> #EXTINF:[duration] [key="key_value"*], title
> [URL_LINK]
> ```

hello i'm using your Git Source files and EPGImporter and normal xml config. 
anyway my xml config works perfect with a ufficial e2m3u2bouquet

**Comment by pepsik-kiev** [comment]
> > **BliNeR-KeY**
> > I have no problem with CrossEPG. All config files are created as needed and everything works as intended. I need a more detailed description of how you got the error as in the screenshot
> > I need an example of any two lines from your playlist
> > ```
> > #EXTINF:[duration] [key="key_value"*], title
> > [URL_LINK]
> > ```
> 
> hello i'm using your Git Source files and EPGImporter and normal xml config.
> anyway my xml config works perfect with a ufficial e2m3u2bouquet

I asked you for an example of a couple of lines from your playlist. All options config.xml you have by default or you have changed something?
Can you describe in more detail how you got this error? Everything works for me without problems. I need more input from you to repeat this error on my receiver.

**Comment by pepsik-kiev** [comment]
> I got this build to run by changing the Picon path to what I use and then changing the testrun paths to match the normal paths. However, it continues to skip channels without TVG-ID in the line on the M3U

The problem of creating playlists in the absence of any of the tags in the extinf playlist is resolved. Is it necessary, for example, to assign channels without a groupe-title to the NoGroup category, or simply ignore and display only when setting "Create all channels bouquet", indicating in the log that the playlist does not contain the group-title tag? Do you have playlists in which the extinf part contains a gruop-title tag and the part does not?

**Comment by pepsik-kiev** [comment]
> I got this build to run by changing the Picon path to what I use and then changing the testrun paths to match the normal paths. However, it continues to skip channels without TVG-ID in the line on the M3U

Try the last changes please. I implemented the logic of processing the absence of the 'group-title' tag in the playlist. Now if it doesn’t exist at all, then "All channels bouquet" is forcibly created despite the settings. If in the playlist the #EXTINF part contains 'group-title' and the part is not, then where it does not exist, “NoGroup” is automatically assigned and userbouquet-NoGroup of the corresponding provider will be created on it. In this case, the creation of “All channels bouquet "- depends on how it is set in the plugin settings. 
There is no dependence when forming bouquets on the presence or absence of certain tags in the #EXTINF line of the playlist. You only need to understand that the presence of the tvg-id tag provides binding to the EPG. If it is no in a playlist, then specify a link to the EPG in the settings - makes no sense.

**Comment by DougMac** [comment]
Closed as to many untested changes to check & merge.

**Pull request closed without merging**
